/**
 * Media Library Tab
 *
 * Unified browser for all media generated by tool services.
 * Shows tool cards with file counts, expandable file grids with thumbnails,
 * lightbox preview, download/open actions, and batch thumbnail generation.
 */
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Image,
  Film,
  Music,
  FileText,
  Archive,
  File,
  FileCode,
  Table,
  Download,
  ExternalLink,
  X,
  ChevronLeft,
  ChevronRight,
  Loader2,
  FolderOpen,
  HardDrive,
  ArrowUpDown,
  Grid,
  List,
  Trash2,
  Eye,
  ChevronDown,
  Play,
} from 'lucide-react';
import { mediaLibraryService } from '@/services/mediaLibrary';
import { useAuthStore } from '@/stores/auth';
import type { ToolMediaSummary, MediaFile, MediaStats } from '@/types';

// =============================================================================
// Constants
// =============================================================================

const MEDIA_TYPE_ICONS: Record<string, { icon: React.ElementType; color: string }> = {
  image: { icon: Image, color: 'text-neon-cyan' },
  video: { icon: Film, color: 'text-purple-400' },
  audio: { icon: Music, color: 'text-neon-green' },
  document: { icon: FileText, color: 'text-yellow-400' },
  archive: { icon: Archive, color: 'text-orange-400' },
  code: { icon: FileCode, color: 'text-blue-400' },
  spreadsheet: { icon: Table, color: 'text-green-400' },
  other: { icon: File, color: 'text-gray-400' },
};

const TOOL_ICON_MAP: Record<string, string> = {
  music: '🎵',
  image: '🖼️',
  video: '🎬',
  audio: '🔊',
  document: '📄',
  archive: '📦',
};

// =============================================================================
// Helpers
// =============================================================================

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

function formatTimeAgo(dateStr: string): string {
  const now = new Date();
  const date = new Date(dateStr);
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  if (diffMins < 1) return 'just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  const diffHrs = Math.floor(diffMins / 60);
  if (diffHrs < 24) return `${diffHrs}h ago`;
  const diffDays = Math.floor(diffHrs / 24);
  if (diffDays < 30) return `${diffDays}d ago`;
  return date.toLocaleDateString();
}

function getMediaTypeIcon(mediaType: string) {
  return MEDIA_TYPE_ICONS[mediaType] || MEDIA_TYPE_ICONS.other;
}

// =============================================================================
// Hook: Authenticated blob URL fetcher
// =============================================================================

/**
 * Fetches a media endpoint with JWT auth and returns a revocable blob URL.
 * Cleans up on unmount / dependency change.
 */
function useAuthBlobUrl(
  fetcher: (() => Promise<string>) | null
): { url: string | null; loading: boolean; error: boolean } {
  const [url, setUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(!!fetcher);
  const [error, setError] = useState(false);

  useEffect(() => {
    if (!fetcher) {
      setUrl(null);
      setLoading(false);
      return;
    }
    let cancelled = false;
    let blobUrl: string | null = null;
    setLoading(true);
    setError(false);

    fetcher()
      .then((u) => {
        if (!cancelled) {
          blobUrl = u;
          setUrl(u);
          setLoading(false);
        } else {
          URL.revokeObjectURL(u);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setError(true);
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
      if (blobUrl) URL.revokeObjectURL(blobUrl);
    };
  }, [fetcher]);

  return { url, loading, error };
}

// =============================================================================
// Thumbnail Image Component with lazy load + fade-in
// =============================================================================

interface ThumbnailImageProps {
  toolSlug: string;
  file: MediaFile;
  className?: string;
}

const ThumbnailImage: React.FC<ThumbnailImageProps> = ({ toolSlug, file, className = '' }) => {
  const { icon: Icon, color } = getMediaTypeIcon(file.media_type);

  const fetcher = useCallback(
    () => file.thumbnail_url
      ? mediaLibraryService.fetchThumbnailBlobUrl(toolSlug, file.filename)
      : Promise.reject('no thumbnail'),
    [toolSlug, file.filename, file.thumbnail_url]
  );

  const { url: thumbUrl, loading, error: errored } = useAuthBlobUrl(
    file.thumbnail_url ? fetcher : null
  );

  if (!file.thumbnail_url || errored) {
    return (
      <div className={`flex items-center justify-center bg-navy-900/60 ${className}`}>
        <Icon className={`h-10 w-10 ${color} opacity-60`} />
      </div>
    );
  }

  return (
    <div className={`relative bg-navy-900/60 ${className}`}>
      {(loading || !thumbUrl) && (
        <div className="absolute inset-0 flex items-center justify-center">
          <Icon className={`h-10 w-10 ${color} opacity-40`} />
        </div>
      )}
      {thumbUrl && (
        <img
          src={thumbUrl}
          alt={file.filename}
          className={`w-full h-full object-cover transition-opacity duration-300 ${
            loading ? 'opacity-0' : 'opacity-100'
          }`}
        />
      )}
    </div>
  );
};

// =============================================================================
// Lightbox Component
// =============================================================================

interface LightboxProps {
  file: MediaFile;
  toolSlug: string;
  files: MediaFile[];
  onClose: () => void;
  onNavigate: (file: MediaFile) => void;
}

const Lightbox: React.FC<LightboxProps> = ({ file, toolSlug, files, onClose, onNavigate }) => {
  const currentIndex = files.findIndex((f) => f.filename === file.filename);

  const fileFetcher = useCallback(
    () => mediaLibraryService.fetchFileBlobUrl(toolSlug, file.filename),
    [toolSlug, file.filename]
  );
  const { url: fileUrl, loading: fileLoading } = useAuthBlobUrl(fileFetcher);

  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
      if (e.key === 'ArrowLeft' && currentIndex > 0) onNavigate(files[currentIndex - 1]);
      if (e.key === 'ArrowRight' && currentIndex < files.length - 1) onNavigate(files[currentIndex + 1]);
    },
    [currentIndex, files, onClose, onNavigate]
  );

  useEffect(() => {
    document.addEventListener('keydown', handleKeyDown);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = '';
    };
  }, [handleKeyDown]);

  const handleDownload = useCallback(async (e: React.MouseEvent) => {
    e.preventDefault();
    try {
      await mediaLibraryService.downloadFile(toolSlug, file.filename);
    } catch {
      // Silently fail — user will see nothing downloaded
    }
  }, [toolSlug, file.filename]);

  const handleOpenNewTab = useCallback(async (e: React.MouseEvent) => {
    e.preventDefault();
    try {
      const blobUrl = await mediaLibraryService.fetchFileBlobUrl(toolSlug, file.filename);
      window.open(blobUrl, '_blank');
    } catch {
      // Silently fail
    }
  }, [toolSlug, file.filename]);

  return (
    <div
      className="fixed inset-0 z-50 bg-black/90 backdrop-blur-sm flex flex-col"
      onClick={onClose}
    >
      {/* Top bar */}
      <div
        className="flex items-center justify-between px-6 py-4 bg-navy-950/90 border-b border-gray-700/50"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center gap-3 text-gray-300 text-sm">
          <span className="font-medium text-white">{file.filename}</span>
          <span className="text-gray-500">·</span>
          <span>{formatBytes(file.size_bytes)}</span>
          <span className="text-gray-500">·</span>
          <span>{formatTimeAgo(file.modified_at)}</span>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleOpenNewTab}
            className="p-2 text-gray-300 hover:text-white transition-colors rounded-lg hover:bg-white/10 border border-transparent hover:border-gray-600"
            title="Open in new tab"
          >
            <ExternalLink className="h-5 w-5" />
          </button>
          <button
            onClick={handleDownload}
            className="p-2 text-gray-300 hover:text-neon-cyan transition-colors rounded-lg hover:bg-neon-cyan/10 border border-transparent hover:border-neon-cyan/30"
            title="Download"
          >
            <Download className="h-5 w-5" />
          </button>
          <button
            onClick={onClose}
            className="ml-2 p-2 text-white bg-white/10 hover:bg-red-500/80 transition-colors rounded-lg border border-gray-600 hover:border-red-400"
            title="Close (Esc)"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex items-center justify-center px-16 py-8 relative">
        {/* Nav arrows */}
        {currentIndex > 0 && (
          <button
            onClick={(e) => { e.stopPropagation(); onNavigate(files[currentIndex - 1]); }}
            className="absolute left-4 p-3 text-white bg-black/50 hover:bg-white/20 rounded-full transition-all border border-white/20 hover:border-white/40 shadow-lg z-10"
          >
            <ChevronLeft className="h-8 w-8" />
          </button>
        )}
        {currentIndex < files.length - 1 && (
          <button
            onClick={(e) => { e.stopPropagation(); onNavigate(files[currentIndex + 1]); }}
            className="absolute right-4 p-3 text-white bg-black/50 hover:bg-white/20 rounded-full transition-all border border-white/20 hover:border-white/40 shadow-lg z-10"
          >
            <ChevronRight className="h-8 w-8" />
          </button>
        )}

        {/* Media display */}
        {fileLoading || !fileUrl ? (
          <div className="flex flex-col items-center gap-4" onClick={(e) => e.stopPropagation()}>
            <Loader2 className="h-12 w-12 text-neon-cyan animate-spin" />
            <p className="text-gray-400 text-sm">Loading preview...</p>
          </div>
        ) : file.media_type === 'image' ? (
          <img
            src={fileUrl}
            alt={file.filename}
            className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          />
        ) : file.media_type === 'video' ? (
          <video
            controls
            autoPlay
            className="max-w-full max-h-full rounded-lg shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          >
            <source src={fileUrl} type={file.mime_type || 'video/mp4'} />
            Your browser does not support the video tag.
          </video>
        ) : file.media_type === 'audio' ? (
          <div className="flex flex-col items-center gap-6" onClick={(e) => e.stopPropagation()}>
            <Music className="h-24 w-24 text-neon-green opacity-40" />
            <audio controls autoPlay className="w-96">
              <source src={fileUrl} type={file.mime_type || 'audio/mpeg'} />
              Your browser does not support the audio element.
            </audio>
            <p className="text-gray-400 text-lg">{file.filename}</p>
          </div>
        ) : (
          <div className="flex flex-col items-center gap-4 text-gray-400" onClick={(e) => e.stopPropagation()}>
            <FileText className="h-24 w-24 opacity-40" />
            <p className="text-lg">{file.filename}</p>
            <p className="text-sm">No preview available for this file type</p>
          </div>
        )}
      </div>

      {/* Bottom counter */}
      <div className="text-center py-3 text-sm text-gray-400">
        {currentIndex + 1} / {files.length} · <span className="text-gray-500">click outside to close</span>
      </div>
    </div>
  );
};

// =============================================================================
// File Tile Component
// =============================================================================

interface FileTileProps {
  file: MediaFile;
  toolSlug: string;
  viewMode: 'grid' | 'list';
  isAdmin: boolean;
  onPreview: (file: MediaFile) => void;
  onDelete: (file: MediaFile) => void;
}

const FileTile: React.FC<FileTileProps> = ({
  file,
  toolSlug,
  viewMode,
  isAdmin,
  onPreview,
  onDelete,
}) => {
  const { icon: Icon, color } = getMediaTypeIcon(file.media_type);
  const canPreview = ['image', 'video', 'audio'].includes(file.media_type);

  const handleDownload = useCallback(async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    try {
      await mediaLibraryService.downloadFile(toolSlug, file.filename);
    } catch { /* silent */ }
  }, [toolSlug, file.filename]);

  const handleOpenNewTab = useCallback(async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    try {
      const blobUrl = await mediaLibraryService.fetchFileBlobUrl(toolSlug, file.filename);
      window.open(blobUrl, '_blank');
    } catch { /* silent */ }
  }, [toolSlug, file.filename]);

  if (viewMode === 'list') {
    return (
      <div className="group flex items-center gap-4 bg-gradient-to-r from-gray-900/90 to-gray-900/50 rounded-lg border border-gray-800 hover:border-neon-cyan/30 transition-all duration-200 p-3">
        {/* Icon / Thumbnail */}
        <div className="w-12 h-12 flex-shrink-0 rounded-lg overflow-hidden">
          {file.thumbnail_url ? (
            <ThumbnailImage toolSlug={toolSlug} file={file} className="w-12 h-12" />
          ) : (
            <div className="w-12 h-12 flex items-center justify-center bg-navy-900/60 rounded-lg">
              <Icon className={`h-6 w-6 ${color}`} />
            </div>
          )}
        </div>

        {/* Info */}
        <div className="flex-1 min-w-0">
          <p className="text-sm font-medium text-white truncate">{file.filename}</p>
          <p className="text-xs text-gray-500">
            {formatBytes(file.size_bytes)} · {formatTimeAgo(file.modified_at)}
          </p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          {canPreview && (
            <button
              onClick={() => onPreview(file)}
              className="p-1.5 text-gray-400 hover:text-neon-cyan rounded-lg hover:bg-white/5"
              title="Preview"
            >
              <Eye className="h-4 w-4" />
            </button>
          )}
          <button
            onClick={handleOpenNewTab}
            className="p-1.5 text-gray-400 hover:text-white rounded-lg hover:bg-white/5"
            title="Open in new tab"
          >
            <ExternalLink className="h-4 w-4" />
          </button>
          <button
            onClick={handleDownload}
            className="p-1.5 text-gray-400 hover:text-neon-cyan rounded-lg hover:bg-white/5"
            title="Download"
          >
            <Download className="h-4 w-4" />
          </button>
          {isAdmin && (
            <button
              onClick={() => onDelete(file)}
              className="p-1.5 text-gray-400 hover:text-neon-pink rounded-lg hover:bg-white/5"
              title="Delete"
            >
              <Trash2 className="h-4 w-4" />
            </button>
          )}
        </div>
      </div>
    );
  }

  // Grid mode
  return (
    <div className="group relative bg-gradient-to-br from-gray-900/90 to-gray-900/50 rounded-xl border border-gray-800 hover:border-neon-cyan/40 transition-all duration-300 overflow-hidden hover:shadow-lg hover:shadow-neon-cyan/10">
      {/* Thumbnail area */}
      <div
        className="aspect-square cursor-pointer relative"
        onClick={() => canPreview && onPreview(file)}
      >
        <ThumbnailImage toolSlug={toolSlug} file={file} className="w-full h-full" />

        {/* Video play overlay */}
        {file.media_type === 'video' && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="w-12 h-12 rounded-full bg-black/60 flex items-center justify-center backdrop-blur-sm group-hover:bg-neon-cyan/20 transition-colors">
              <Play className="h-5 w-5 text-white ml-0.5" />
            </div>
          </div>
        )}

        {/* Hover overlay with actions */}
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-200">
          <div className="absolute bottom-2 right-2 flex gap-1">
            {canPreview && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onPreview(file);
                }}
                className="p-1.5 bg-black/60 hover:bg-neon-cyan/30 text-white rounded-lg backdrop-blur-sm transition-colors"
                title="Preview"
              >
                <Eye className="h-4 w-4" />
              </button>
            )}
            <button
              onClick={handleOpenNewTab}
              className="p-1.5 bg-black/60 hover:bg-white/20 text-white rounded-lg backdrop-blur-sm transition-colors"
              title="Open in new tab"
            >
              <ExternalLink className="h-4 w-4" />
            </button>
            <button
              onClick={handleDownload}
              className="p-1.5 bg-black/60 hover:bg-neon-cyan/30 text-white rounded-lg backdrop-blur-sm transition-colors"
              title="Download"
            >
              <Download className="h-4 w-4" />
            </button>
            {isAdmin && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onDelete(file);
                }}
                className="p-1.5 bg-black/60 hover:bg-neon-pink/30 text-white rounded-lg backdrop-blur-sm transition-colors"
                title="Delete"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* File info footer */}
      <div className="p-3 border-t border-gray-800">
        <p className="text-sm text-white truncate font-medium" title={file.filename}>
          {file.filename}
        </p>
        <div className="flex items-center justify-between mt-1">
          <span className="text-xs text-gray-500">{formatBytes(file.size_bytes)}</span>
          <span className="text-xs text-gray-500">{formatTimeAgo(file.modified_at)}</span>
        </div>
      </div>
    </div>
  );
};

// =============================================================================
// Tool Card Component (Overview)
// =============================================================================

interface ToolCardProps {
  tool: ToolMediaSummary;
  onClick: () => void;
}

const ToolCard: React.FC<ToolCardProps> = ({ tool, onClick }) => {
  const toolEmoji = TOOL_ICON_MAP[tool.icon] || '📁';

  return (
    <button
      onClick={onClick}
      className="group w-full text-left bg-gradient-to-br from-gray-900/90 to-gray-900/50 backdrop-blur-sm rounded-xl border border-gray-800 hover:border-neon-cyan/50 transition-all duration-300 p-5 hover:shadow-lg hover:shadow-neon-cyan/20"
    >
      <div className="flex items-start gap-4">
        <span className="text-3xl flex-shrink-0">{toolEmoji}</span>
        <div className="flex-1 min-w-0">
          <h3 className="font-semibold text-white group-hover:text-neon-cyan transition-colors">
            {tool.display_name}
          </h3>
          <div className="flex items-center gap-3 mt-2">
            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium bg-neon-cyan/10 text-neon-cyan border border-neon-cyan/30 rounded-full">
              {tool.file_count} {tool.file_count === 1 ? 'file' : 'files'}
            </span>
            <span className="text-xs text-gray-500">
              {formatBytes(tool.total_size_bytes)}
            </span>
          </div>
          {tool.newest_file_date && (
            <p className="text-xs text-gray-500 mt-2">
              Latest: {formatTimeAgo(tool.newest_file_date)}
            </p>
          )}
          {/* Media type chips */}
          <div className="flex gap-1.5 mt-3">
            {tool.media_types.map((type) => {
              const { icon: Icon, color } = getMediaTypeIcon(type);
              return (
                <span
                  key={type}
                  className="inline-flex items-center gap-1 px-2 py-0.5 text-xs bg-gray-800/50 text-gray-400 rounded-full"
                >
                  <Icon className={`h-3 w-3 ${color}`} />
                  {type}
                </span>
              );
            })}
          </div>
        </div>
        <ChevronRight className="h-5 w-5 text-gray-600 group-hover:text-neon-cyan transition-colors flex-shrink-0 mt-1" />
      </div>
    </button>
  );
};

// =============================================================================
// Stats Bar Component
// =============================================================================

interface StatsBarProps {
  stats: MediaStats | undefined;
  isLoading: boolean;
}

const StatsBar: React.FC<StatsBarProps> = ({ stats, isLoading }) => {
  if (isLoading || !stats) return null;

  return (
    <div className="flex flex-wrap items-center gap-4 px-5 py-3 bg-navy-800/50 rounded-xl border border-gray-800">
      <div className="flex items-center gap-2">
        <HardDrive className="h-4 w-4 text-neon-cyan" />
        <span className="text-sm text-white font-medium">{stats.total_files} files</span>
        <span className="text-xs text-gray-500">({formatBytes(stats.total_size_bytes)})</span>
      </div>
      <div className="h-4 w-px bg-gray-700" />
      {(Object.entries(stats.by_type) as [string, number][])
        .sort(([, a], [, b]) => b - a)
        .map(([type, count]) => {
          const { icon: Icon, color } = getMediaTypeIcon(type);
          return (
            <span
              key={type}
              className="inline-flex items-center gap-1.5 text-xs text-gray-400"
            >
              <Icon className={`h-3.5 w-3.5 ${color}`} />
              {count} {type}
            </span>
          );
        })}
    </div>
  );
};

// =============================================================================
// Main MediaLibraryTab Component
// =============================================================================

type SortBy = 'modified_at' | 'name' | 'size';
type SortOrder = 'asc' | 'desc';

export const MediaLibraryTab: React.FC = () => {
  const { user } = useAuthStore();
  const queryClient = useQueryClient();
  const isAdmin = user?.role === 'admin';

  // State
  const [selectedTool, setSelectedTool] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');
  const [sortBy, setSortBy] = useState<SortBy>('modified_at');
  const [sortOrder, setSortOrder] = useState<SortOrder>('desc');
  const [mediaTypeFilter, setMediaTypeFilter] = useState<string | undefined>(undefined);
  const [lightboxFile, setLightboxFile] = useState<MediaFile | null>(null);
  const [page, setPage] = useState(1);
  const thumbnailsTriggered = useRef<Set<string>>(new Set());

  // Reset page when filters change
  useEffect(() => {
    setPage(1);
  }, [sortBy, sortOrder, mediaTypeFilter, selectedTool]);

  // Queries
  const { data: tools, isLoading: toolsLoading } = useQuery({
    queryKey: ['media-library', 'tools'],
    queryFn: () => mediaLibraryService.listToolsWithMedia(),
    refetchInterval: 30000,
  });

  const { data: stats, isLoading: statsLoading } = useQuery({
    queryKey: ['media-library', 'stats'],
    queryFn: () => mediaLibraryService.getStats(),
  });

  const { data: fileList, isLoading: filesLoading } = useQuery({
    queryKey: ['media-library', 'files', selectedTool, page, sortBy, sortOrder, mediaTypeFilter],
    queryFn: () =>
      mediaLibraryService.listFiles(selectedTool!, {
        page,
        page_size: 50,
        sort_by: sortBy,
        sort_order: sortOrder,
        media_type: mediaTypeFilter,
      }),
    enabled: !!selectedTool,
    refetchInterval: 15000, // Refresh to pick up thumbnail changes
  });

  // Auto-trigger thumbnail generation for the selected tool
  useEffect(() => {
    if (selectedTool && fileList && !thumbnailsTriggered.current.has(selectedTool)) {
      const needsThumbnails = fileList.files.some(
        (f) => !f.has_thumbnail && ['image', 'video', 'audio'].includes(f.media_type)
      );
      if (needsThumbnails) {
        thumbnailsTriggered.current.add(selectedTool);
        mediaLibraryService.generateThumbnails(selectedTool).catch(() => {
          // Non-critical — thumbnails will be generated on-demand
        });
      }
    }
  }, [selectedTool, fileList]);

  // Find selected tool metadata
  const selectedToolMeta = tools?.find((t) => t.slug === selectedTool);

  // Handlers
  const handleDeleteFile = async (file: MediaFile) => {
    if (!selectedTool) return;
    if (!window.confirm(`Delete ${file.filename}? This cannot be undone.`)) return;
    try {
      await mediaLibraryService.deleteFile(selectedTool, file.filename);
      queryClient.invalidateQueries({ queryKey: ['media-library'] });
    } catch {
      // Error handled by API client interceptor
    }
  };

  const handleToolClick = (slug: string) => {
    setSelectedTool(slug);
    setPage(1);
    setMediaTypeFilter(undefined);
  };

  const handleBack = () => {
    setSelectedTool(null);
    setMediaTypeFilter(undefined);
    setPage(1);
  };

  // Get all previewable files for lightbox navigation
  const previewableFiles =
    fileList?.files.filter((f) => ['image', 'video', 'audio'].includes(f.media_type)) || [];

  // =====================================================================
  // Render: Loading State
  // =====================================================================

  if (toolsLoading) {
    return (
      <div className="flex items-center justify-center py-16">
        <Loader2 className="h-8 w-8 animate-spin text-neon-cyan" />
      </div>
    );
  }

  // =====================================================================
  // Render: Tool Files View
  // =====================================================================

  if (selectedTool && selectedToolMeta) {
    return (
      <div className="space-y-5">
        {/* Breadcrumb / Back navigation */}
        <div className="flex items-center gap-3">
          <button
            onClick={handleBack}
            className="inline-flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-neon-cyan bg-neon-cyan/10 hover:bg-neon-cyan/20 border border-neon-cyan/30 hover:border-neon-cyan/50 rounded-lg transition-colors"
          >
            <ChevronLeft className="h-5 w-5" />
            Media Library
          </button>
          <span className="text-gray-600 text-lg">/</span>
          <span className="text-white font-semibold text-base">{selectedToolMeta.display_name}</span>
          <span className="text-gray-400 text-sm">
            ({fileList?.total_count ?? 0} files · {formatBytes(fileList?.total_size_bytes ?? 0)})
          </span>
        </div>

        {/* Controls */}
        <div className="flex flex-wrap items-center gap-3">
          {/* Media type filter chips */}
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={() => setMediaTypeFilter(undefined)}
              className={`px-3 py-1.5 text-xs font-medium rounded-full border transition-colors ${
                !mediaTypeFilter
                  ? 'bg-neon-cyan/10 text-neon-cyan border-neon-cyan/30'
                  : 'bg-gray-800/50 text-gray-400 border-gray-700 hover:text-white hover:border-gray-500'
              }`}
            >
              All
            </button>
            {['image', 'video', 'audio', 'document'].map((type) => {
              const { icon: Icon, color } = getMediaTypeIcon(type);
              return (
                <button
                  key={type}
                  onClick={() => setMediaTypeFilter(type === mediaTypeFilter ? undefined : type)}
                  className={`px-3 py-1.5 text-xs font-medium rounded-full border transition-colors flex items-center gap-1.5 ${
                    mediaTypeFilter === type
                      ? 'bg-neon-cyan/10 text-neon-cyan border-neon-cyan/30'
                      : 'bg-gray-800/50 text-gray-400 border-gray-700 hover:text-white hover:border-gray-500'
                  }`}
                >
                  <Icon className={`h-3 w-3 ${mediaTypeFilter === type ? 'text-neon-cyan' : color}`} />
                  {type.charAt(0).toUpperCase() + type.slice(1)}
                </button>
              );
            })}
          </div>

          <div className="flex-1" />

          {/* Sort */}
          <div className="flex items-center gap-2">
            <ArrowUpDown className="h-4 w-4 text-gray-500" />
            <select
              value={`${sortBy}-${sortOrder}`}
              onChange={(e) => {
                const [by, order] = e.target.value.split('-') as [SortBy, SortOrder];
                setSortBy(by);
                setSortOrder(order);
              }}
              className="px-3 py-1.5 text-xs bg-gray-900/50 border border-gray-700 rounded-lg text-white focus:border-neon-cyan"
            >
              <option value="modified_at-desc">Newest First</option>
              <option value="modified_at-asc">Oldest First</option>
              <option value="name-asc">Name A-Z</option>
              <option value="name-desc">Name Z-A</option>
              <option value="size-desc">Largest First</option>
              <option value="size-asc">Smallest First</option>
            </select>
          </div>

          {/* View toggle */}
          <div className="flex items-center gap-1">
            <button
              onClick={() => setViewMode('grid')}
              className={`p-1.5 rounded-lg transition-colors ${
                viewMode === 'grid'
                  ? 'bg-neon-cyan/20 text-neon-cyan'
                  : 'bg-gray-900/50 text-gray-400 hover:text-white'
              }`}
            >
              <Grid className="h-4 w-4" />
            </button>
            <button
              onClick={() => setViewMode('list')}
              className={`p-1.5 rounded-lg transition-colors ${
                viewMode === 'list'
                  ? 'bg-neon-cyan/20 text-neon-cyan'
                  : 'bg-gray-900/50 text-gray-400 hover:text-white'
              }`}
            >
              <List className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* File grid/list */}
        {filesLoading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-8 w-8 animate-spin text-neon-cyan" />
          </div>
        ) : !fileList || fileList.files.length === 0 ? (
          <div className="text-center py-16">
            <FolderOpen className="h-16 w-16 mx-auto mb-4 text-gray-600" />
            <h3 className="text-lg font-semibold text-gray-400 mb-2">No files yet</h3>
            <p className="text-gray-500 text-sm">
              Run this tool from the Workbench to generate media
            </p>
          </div>
        ) : viewMode === 'grid' ? (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-4">
            {fileList.files.map((file) => (
              <FileTile
                key={file.filename}
                file={file}
                toolSlug={selectedTool}
                viewMode="grid"
                isAdmin={isAdmin}
                onPreview={(f) => setLightboxFile(f)}
                onDelete={handleDeleteFile}
              />
            ))}
          </div>
        ) : (
          <div className="space-y-2">
            {fileList.files.map((file) => (
              <FileTile
                key={file.filename}
                file={file}
                toolSlug={selectedTool}
                viewMode="list"
                isAdmin={isAdmin}
                onPreview={(f) => setLightboxFile(f)}
                onDelete={handleDeleteFile}
              />
            ))}
          </div>
        )}

        {/* Pagination */}
        {fileList && fileList.total_count > fileList.page_size && (
          <div className="flex items-center justify-center gap-4 pt-4">
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page <= 1}
              className="px-4 py-2 text-sm bg-gray-900/50 border border-gray-700 rounded-lg text-gray-400 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed"
            >
              Previous
            </button>
            <span className="text-sm text-gray-500">
              Page {page} of {Math.ceil(fileList.total_count / fileList.page_size)}
            </span>
            <button
              onClick={() => setPage((p) => p + 1)}
              disabled={!fileList.has_more}
              className="px-4 py-2 text-sm bg-gray-900/50 border border-gray-700 rounded-lg text-gray-400 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed"
            >
              Next
            </button>
          </div>
        )}

        {/* Lightbox */}
        {lightboxFile && selectedTool && (
          <Lightbox
            file={lightboxFile}
            toolSlug={selectedTool}
            files={previewableFiles}
            onClose={() => setLightboxFile(null)}
            onNavigate={(f) => setLightboxFile(f)}
          />
        )}
      </div>
    );
  }

  // =====================================================================
  // Render: Overview (Tool Cards)
  // =====================================================================

  const toolsWithFiles = tools?.filter((t) => t.file_count > 0) || [];
  const toolsEmpty = tools?.filter((t) => t.file_count === 0) || [];

  return (
    <div className="space-y-6">
      {/* Global stats */}
      <StatsBar stats={stats} isLoading={statsLoading} />

      {/* Tools with files */}
      {toolsWithFiles.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {toolsWithFiles.map((tool) => (
            <ToolCard key={tool.slug} tool={tool} onClick={() => handleToolClick(tool.slug)} />
          ))}
        </div>
      ) : (
        <div className="text-center py-16">
          <FolderOpen className="h-20 w-20 mx-auto mb-4 text-gray-600" />
          <h3 className="text-xl font-semibold text-gray-400 mb-2">No generated media yet</h3>
          <p className="text-gray-500">
            Run tools from the Workbench to start generating images, videos, audio, and more
          </p>
        </div>
      )}

      {/* Collapsed section for tools with no files */}
      {toolsEmpty.length > 0 && toolsWithFiles.length > 0 && (
        <EmptyToolsSection tools={toolsEmpty} />
      )}
    </div>
  );
};

// =============================================================================
// Collapsible empty tools section
// =============================================================================

const EmptyToolsSection: React.FC<{ tools: ToolMediaSummary[] }> = ({ tools }) => {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="border-t border-gray-800 pt-4">
      <button
        onClick={() => setExpanded(!expanded)}
        className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-300 transition-colors"
      >
        <ChevronDown
          className={`h-4 w-4 transition-transform ${expanded ? 'rotate-180' : ''}`}
        />
        {tools.length} tool{tools.length !== 1 ? 's' : ''} with no output files
      </button>
      {expanded && (
        <div className="mt-3 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
          {tools.map((tool) => (
            <div
              key={tool.slug}
              className="flex items-center gap-2 px-3 py-2 bg-gray-900/30 rounded-lg border border-gray-800/50 text-gray-500 text-sm"
            >
              <span>{TOOL_ICON_MAP[tool.icon] || '📁'}</span>
              <span className="truncate">{tool.display_name}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default MediaLibraryTab;
