"""add_tool_interface_config

Revision ID: a25843b26383
Revises: c3f5a9b12d4e
Create Date: 2026-01-30 17:53:01.320225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a25843b26383'
down_revision = 'c3f5a9b12d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_definitions', 'expected_run_duration_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Expected agent run duration in minutes. Used for staleness detection.',
               existing_nullable=True)
    op.alter_column('job_queue', 'expected_duration_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Expected job duration in minutes. Used for staleness detection with padding.',
               existing_nullable=True)
    op.drop_index('ix_storage_files_agent_name', table_name='storage_files')
    op.create_index(op.f('ix_tool_discovery_strategies_status'), 'tool_discovery_strategies', ['status'], unique=False)
    op.create_index(op.f('ix_tool_knowledge_category'), 'tool_knowledge', ['category'], unique=False)
    op.create_index(op.f('ix_tool_knowledge_related_tool_id'), 'tool_knowledge', ['related_tool_id'], unique=False)
    op.create_index(op.f('ix_tool_knowledge_status'), 'tool_knowledge', ['status'], unique=False)
    op.add_column('tools', sa.Column('interface_type', sa.String(length=50), nullable=True))
    op.add_column('tools', sa.Column('interface_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tools', sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tools', sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tools', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'timeout_seconds')
    op.drop_column('tools', 'output_schema')
    op.drop_column('tools', 'input_schema')
    op.drop_column('tools', 'interface_config')
    op.drop_column('tools', 'interface_type')
    op.drop_index(op.f('ix_tool_knowledge_status'), table_name='tool_knowledge')
    op.drop_index(op.f('ix_tool_knowledge_related_tool_id'), table_name='tool_knowledge')
    op.drop_index(op.f('ix_tool_knowledge_category'), table_name='tool_knowledge')
    op.drop_index(op.f('ix_tool_discovery_strategies_status'), table_name='tool_discovery_strategies')
    op.create_index('ix_storage_files_agent_name', 'storage_files', ['agent_name'], unique=False)
    op.alter_column('job_queue', 'expected_duration_minutes',
               existing_type=sa.INTEGER(),
               comment='Expected job duration in minutes. Used for staleness detection with padding.',
               existing_nullable=True)
    op.alter_column('agent_definitions', 'expected_run_duration_minutes',
               existing_type=sa.INTEGER(),
               comment='Expected agent run duration in minutes. Used for staleness detection.',
               existing_nullable=True)
    # ### end Alembic commands ###
