"""add_opportunity_scout_models

Revision ID: fcf067eaa4ce
Revises: 3471625181e9
Create Date: 2026-01-28 22:10:41.836621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcf067eaa4ce'
down_revision = '3471625181e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insight_type', sa.Enum('principle', 'pattern', 'anti_pattern', 'hypothesis', 'validated', name='insight_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('times_confirmed', sa.Integer(), nullable=False),
    sa.Column('times_contradicted', sa.Integer(), nullable=False),
    sa.Column('parent_insight_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_insight_id'], ['agent_insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['agent_insights.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_insights_insight_type'), 'agent_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_agent_insights_title'), 'agent_insights', ['title'], unique=False)
    op.create_index('ix_agent_insights_type_confidence', 'agent_insights', ['insight_type', 'confidence'], unique=False)
    op.create_table('discovery_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'retired', 'experimental', name='strategy_status'), nullable=False),
    sa.Column('times_executed', sa.Integer(), nullable=False),
    sa.Column('last_executed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opportunities_found', sa.Integer(), nullable=False),
    sa.Column('opportunities_approved', sa.Integer(), nullable=False),
    sa.Column('opportunities_rejected', sa.Integer(), nullable=False),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('improvement_ideas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_strategy_id', sa.UUID(), nullable=True),
    sa.Column('child_strategy_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['parent_strategy_id'], ['discovery_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_strategies_name'), 'discovery_strategies', ['name'], unique=False)
    op.create_index(op.f('ix_discovery_strategies_status'), 'discovery_strategies', ['status'], unique=False)
    op.create_index('ix_discovery_strategies_status_effectiveness', 'discovery_strategies', ['status', 'effectiveness_score'], unique=False)
    op.create_table('memory_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_type', sa.Enum('weekly', 'monthly', 'quarterly', 'annual', name='summary_type'), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('top_strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failed_strategies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities_found', sa.Integer(), nullable=False),
    sa.Column('opportunities_approved', sa.Integer(), nullable=False),
    sa.Column('opportunities_rejected', sa.Integer(), nullable=False),
    sa.Column('proposals_created', sa.Integer(), nullable=False),
    sa.Column('successful_campaigns', sa.Integer(), nullable=False),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avoid_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experiments_suggested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detailed_records_archived', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_summaries_period_end'), 'memory_summaries', ['period_end'], unique=False)
    op.create_index(op.f('ix_memory_summaries_period_start'), 'memory_summaries', ['period_start'], unique=False)
    op.create_index(op.f('ix_memory_summaries_summary_type'), 'memory_summaries', ['summary_type'], unique=False)
    op.create_table('scoring_rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opportunities_scored', sa.Integer(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=True),
    sa.Column('evolved_from_id', sa.UUID(), nullable=True),
    sa.Column('evolution_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evolved_from_id'], ['scoring_rubrics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_rubrics_is_active'), 'scoring_rubrics', ['is_active'], unique=False)
    op.create_table('user_scout_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_active_proposals', sa.Integer(), nullable=False),
    sa.Column('hopper_warning_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_pause_discovery', sa.Boolean(), nullable=False),
    sa.Column('auto_dismiss_below_score', sa.Float(), nullable=False),
    sa.Column('auto_dismiss_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_sort', sa.String(length=50), nullable=False),
    sa.Column('show_unlikely_tier', sa.Boolean(), nullable=False),
    sa.Column('preferred_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excluded_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_rubric_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovery_strategy_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_query', sa.Text(), nullable=True),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_signal', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('opportunity_type', sa.Enum('arbitrage', 'content', 'service', 'product', 'automation', 'affiliate', 'investment', 'other', name='opportunity_type'), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'researching', 'evaluated', 'presented', 'approved', 'rejected', 'expired', 'merged', name='opportunity_status'), nullable=False),
    sa.Column('initial_assessment', sa.Text(), nullable=True),
    sa.Column('detailed_analysis', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('time_sensitivity', sa.Enum('immediate', 'short', 'medium', 'evergreen', name='time_sensitivity'), nullable=True),
    sa.Column('estimated_effort', sa.Enum('minimal', 'moderate', 'significant', 'major', name='effort_level'), nullable=True),
    sa.Column('estimated_revenue_potential', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('ranking_tier', sa.Enum('top_pick', 'promising', 'maybe', 'unlikely', name='ranking_tier'), nullable=True),
    sa.Column('ranking_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('required_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocking_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('presented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_decision', sa.String(length=50), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('similar_opportunity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('derived_from_id', sa.UUID(), nullable=True),
    sa.Column('bulk_dismissed', sa.Boolean(), nullable=False),
    sa.Column('bulk_dismiss_reason', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['derived_from_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['discovery_strategy_id'], ['discovery_strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_discovered_at'), 'opportunities', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_opportunities_discovery_strategy_id'), 'opportunities', ['discovery_strategy_id'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_overall_score'), 'opportunities', ['overall_score'], unique=False)
    op.create_index('ix_opportunities_presented_at', 'opportunities', ['presented_at'], unique=False)
    op.create_index(op.f('ix_opportunities_ranking_tier'), 'opportunities', ['ranking_tier'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index('ix_opportunities_status_score', 'opportunities', ['status', 'overall_score'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index('ix_opportunities_user_decision', 'opportunities', ['user_decision'], unique=False)
    op.create_table('strategy_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('queries_run', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('opportunities_discovered', sa.Integer(), nullable=False),
    sa.Column('quality_assessment', sa.Text(), nullable=True),
    sa.Column('user_decision', sa.String(length=50), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_failed', sa.Text(), nullable=True),
    sa.Column('suggested_adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['discovery_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_outcomes_executed_at'), 'strategy_outcomes', ['executed_at'], unique=False)
    op.create_index(op.f('ix_strategy_outcomes_strategy_id'), 'strategy_outcomes', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_outcomes_strategy_id'), table_name='strategy_outcomes')
    op.drop_index(op.f('ix_strategy_outcomes_executed_at'), table_name='strategy_outcomes')
    op.drop_table('strategy_outcomes')
    op.drop_index('ix_opportunities_user_decision', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index('ix_opportunities_status_score', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_ranking_tier'), table_name='opportunities')
    op.drop_index('ix_opportunities_presented_at', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_overall_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_discovery_strategy_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_discovered_at'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('user_scout_settings')
    op.drop_index(op.f('ix_scoring_rubrics_is_active'), table_name='scoring_rubrics')
    op.drop_table('scoring_rubrics')
    op.drop_index(op.f('ix_memory_summaries_summary_type'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_period_start'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_period_end'), table_name='memory_summaries')
    op.drop_table('memory_summaries')
    op.drop_index('ix_discovery_strategies_status_effectiveness', table_name='discovery_strategies')
    op.drop_index(op.f('ix_discovery_strategies_status'), table_name='discovery_strategies')
    op.drop_index(op.f('ix_discovery_strategies_name'), table_name='discovery_strategies')
    op.drop_table('discovery_strategies')
    op.drop_index('ix_agent_insights_type_confidence', table_name='agent_insights')
    op.drop_index(op.f('ix_agent_insights_title'), table_name='agent_insights')
    op.drop_index(op.f('ix_agent_insights_insight_type'), table_name='agent_insights')
    op.drop_table('agent_insights')
    # ### end Alembic commands ###
