"""add_ideas_and_strategic_context

Revision ID: 6f201faa229d
Revises: f18e6e3fe95b
Create Date: 2026-01-29 12:52:52.496233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f201faa229d'
down_revision = 'f18e6e3fe95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategic_context_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('use_count', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_context_entries_category'), 'strategic_context_entries', ['category'], unique=False)
    op.create_index('ix_strategic_context_relevance', 'strategic_context_entries', ['relevance_score'], unique=False)
    op.create_index('ix_strategic_context_user_category', 'strategic_context_entries', ['user_id', 'category'], unique=False)
    op.create_table('user_ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('reformatted_content', sa.Text(), nullable=False),
    sa.Column('distilled_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_conversation_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_agent', sa.String(length=50), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategic_context_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategic_context_id'], ['strategic_context_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_ideas_created', 'user_ideas', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_ideas_status'), 'user_ideas', ['status'], unique=False)
    op.create_index('ix_user_ideas_user_status', 'user_ideas', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_ideas_user_status', table_name='user_ideas')
    op.drop_index(op.f('ix_user_ideas_status'), table_name='user_ideas')
    op.drop_index('ix_user_ideas_created', table_name='user_ideas')
    op.drop_table('user_ideas')
    op.drop_index('ix_strategic_context_user_category', table_name='strategic_context_entries')
    op.drop_index('ix_strategic_context_relevance', table_name='strategic_context_entries')
    op.drop_index(op.f('ix_strategic_context_entries_category'), table_name='strategic_context_entries')
    op.drop_table('strategic_context_entries')
    # ### end Alembic commands ###
