"""add_proposal_research_context_and_scout_status

Revision ID: 6cebfae7cf42
Revises: a1b2c3d4e5f6
Create Date: 2026-01-29 07:20:08.279146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cebfae7cf42'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add new proposal status value to enum
    op.execute("ALTER TYPE proposal_status ADD VALUE IF NOT EXISTS 'draft_from_scout'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_definitions_status'), 'agent_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.add_column('proposals', sa.Column('research_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proposals', sa.Column('source_opportunity_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_proposals_source_opportunity_id'), 'proposals', ['source_opportunity_id'], unique=False)
    op.create_foreign_key('fk_proposals_source_opportunity', 'proposals', 'opportunities', ['source_opportunity_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_proposals_source_opportunity', 'proposals', type_='foreignkey')
    op.drop_index(op.f('ix_proposals_source_opportunity_id'), table_name='proposals')
    op.drop_column('proposals', 'source_opportunity_id')
    op.drop_column('proposals', 'research_context')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_definitions_status'), table_name='agent_definitions')
    # Note: Cannot remove enum value in PostgreSQL
    # ### end Alembic commands ###
