"""add_resources_and_job_queue

Revision ID: 4720000c2f76
Revises: 57ff22666b9d
Create Date: 2026-01-28 17:39:51.066012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4720000c2f76'
down_revision = '57ff22666b9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create resources table
    op.create_table(
        'resources',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('is_system_resource', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=True)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)

    # Add resource_id to tools_catalog
    op.add_column('tools', sa.Column('resource_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_tools_resource_id', 'tools', 'resources', ['resource_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tools_resource_id'), 'tools', ['resource_id'], unique=False)

    # Create job_queue table
    op.create_table(
        'job_queue',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tool_id', sa.UUID(), nullable=False),
        sa.Column('resource_id', sa.UUID(), nullable=False),
        sa.Column('conversation_id', sa.UUID(), nullable=False),
        sa.Column('message_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_job_queue_status'), 'job_queue', ['status'], unique=False)
    op.create_index(op.f('ix_job_queue_resource_id'), 'job_queue', ['resource_id'], unique=False)
    op.create_index(op.f('ix_job_queue_queued_at'), 'job_queue', ['queued_at'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_user_id', table_name='conversations', if_exists=True)
    op.create_index(op.f('ix_conversations_created_by_user_id'), 'conversations', ['created_by_user_id'], unique=False)
    op.drop_index('idx_messages_has_attachments', table_name='messages', postgresql_where='(jsonb_array_length(attachments) > 0)', if_exists=True)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages', if_exists=True)
    op.create_index('idx_messages_has_attachments', 'messages', [sa.text('(jsonb_array_length(attachments) > 0)')], unique=False, postgresql_where='(jsonb_array_length(attachments) > 0)')
    op.drop_index(op.f('ix_conversations_created_by_user_id'), table_name='conversations', if_exists=True)
    op.create_index('ix_conversations_user_id', 'conversations', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###

    # Drop job_queue table
    op.drop_index(op.f('ix_job_queue_queued_at'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_resource_id'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_status'), table_name='job_queue')
    op.drop_table('job_queue')

    # Remove resource_id from tools_catalog
    op.drop_index(op.f('ix_tools_resource_id'), table_name='tools')
    op.drop_constraint('fk_tools_resource_id', 'tools', type_='foreignkey')
    op.drop_column('tools', 'resource_id')

    # Drop resources table
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_table('resources')
