"""add_user_role

Revision ID: 723ca881044e
Revises: ae49b72c3db9
Create Date: 2026-01-28 05:03:31.772302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723ca881044e'
down_revision = 'ae49b72c3db9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'proposals', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'proposals', 'users', ['user_id'], ['id'])
    
    # Add role column as nullable first
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    
    # Set existing users to 'admin' role and activate them
    op.execute("UPDATE users SET role = 'admin', is_active = true WHERE role IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('users', 'role', nullable=False)
    
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    # ### end Alembic commands ###
