import type { Proposal, User, Tool } from '@/types';

export const mockUser: User = {
  id: '123e4567-e89b-12d3-a456-426614174000',
  email: 'test@example.com',
  username: 'testuser',
  role: 'user',
  is_active: true,
  is_superuser: false,
  last_login: '2026-01-28T12:00:00Z',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-28T12:00:00Z',
};

export const mockAdminUser: User = {
  ...mockUser,
  id: 'admin-123e4567-e89b-12d3-a456-426614174000',
  email: 'admin@example.com',
  username: 'adminuser',
  role: 'admin',
};

export const mockProposal: Proposal = {
  id: 'prop-123e4567-e89b-12d3-a456-426614174000',
  user_id: '123e4567-e89b-12d3-a456-426614174000',
  agent_id: null,
  title: 'Test Proposal: AI Blog Campaign',
  summary: 'Automated blog content generation using GPT-4',
  detailed_description: 'This is a comprehensive test proposal for automated blog content generation using GPT-4. It includes automated posting, SEO optimization, and analytics tracking.',
  status: 'pending',
  initial_budget: 500,
  recurring_costs: { monthly_hosting: 50, api_costs: 100 },
  expected_returns: { monthly: 2000, annual: 24000 },
  risk_level: 'low',
  risk_description: 'Low risk due to established technology and proven market demand.',
  stop_loss_threshold: { max_loss: 300, time_limit_days: 30 },
  success_criteria: { min_revenue: 1000, target_roi: 2.0 },
  required_tools: { openai: 'GPT-4 access', wordpress: 'Blog hosting' },
  required_inputs: { api_keys: ['OPENAI_API_KEY'], accounts: ['wordpress_admin'] },
  implementation_timeline: { phase1: 'Setup (1 week)', phase2: 'Launch (2 weeks)' },
  similar_proposals: null,
  similarity_score: null,
  source: 'manual',
  tags: { category: 'content', priority: 'medium' },
  meta_data: null,
  submitted_at: '2026-01-28T10:00:00Z',
  reviewed_at: null,
  created_at: '2026-01-28T10:00:00Z',
  updated_at: '2026-01-28T10:00:00Z',
};

export const mockProposals: Proposal[] = [
  mockProposal,
  {
    ...mockProposal,
    id: 'prop-223e4567-e89b-12d3-a456-426614174001',
    title: 'YouTube Shorts Automation',
    summary: 'Automated short-form video generation and posting',
    status: 'approved',
    risk_level: 'medium',
    initial_budget: 1000,
    expected_returns: { monthly: 3000 },
  },
  {
    ...mockProposal,
    id: 'prop-323e4567-e89b-12d3-a456-426614174002',
    title: 'Social Media Management Bot',
    summary: 'AI-powered social media posting and engagement',
    status: 'under_review',
    risk_level: 'high',
    initial_budget: 750,
    expected_returns: { monthly: 1500 },
  },
];

// Mock API responses
export const mockApiResponses = {
  proposals: {
    list: mockProposals,
    single: mockProposal,
    create: mockProposal,
    update: { ...mockProposal, status: 'approved' },
  },
};

export const mockTool: Tool = {
  id: 'tool-123e4567-e89b-12d3-a456-426614174000',
  name: 'OpenAI GPT-4 API',
  slug: 'openai-gpt-4-api',
  category: 'api',
  description: 'Access to OpenAI GPT-4 API for content generation and analysis',
  tags: ['ai', 'nlp', 'generation'],
  status: 'requested',
  requester_id: '123e4567-e89b-12d3-a456-426614174000',
  assigned_to_id: null,
  approved_by_id: null,
  implementation_notes: null,
  blockers: null,
  dependencies: null,
  requested_at: '2026-01-28T10:00:00Z',
  approved_at: null,
  implemented_at: null,
  estimated_completion_date: null,
  usage_instructions: '# Usage\n\nCall the API with your prompt:\n```python\nresponse = openai.chat.completions.create(...)\n```',
  example_code: '```python\nimport openai\n\nclient = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))\nresponse = client.chat.completions.create(\n  model="gpt-4",\n  messages=[{"role": "user", "content": "Hello"}]\n)\n```',
  required_environment_variables: { OPENAI_API_KEY: 'Your OpenAI API key' },
  integration_complexity: 'low',
  cost_model: 'Pay per token',
  cost_details: { input_tokens: '$0.03/1K', output_tokens: '$0.06/1K' },
  shared_resources: null,
  strengths: 'State-of-the-art language understanding, versatile, well-documented',
  weaknesses: 'Can be expensive at scale, rate limits on free tier',
  best_use_cases: 'Content generation, chatbots, text analysis, summarization',
  external_documentation_url: 'https://platform.openai.com/docs',
  version: '1.0.0',
  priority: 'high',
  created_at: '2026-01-28T10:00:00Z',
  updated_at: '2026-01-28T10:00:00Z',
  requester_username: 'testuser',
  assigned_to_username: null,
  unread_count: 0,
};

export const mockTools: Tool[] = [
  mockTool,
  {
    ...mockTool,
    id: 'tool-223e4567-e89b-12d3-a456-426614174001',
    name: 'Google Sheets API',
    slug: 'google-sheets-api',
    category: 'data_source',
    description: 'Read and write data to Google Sheets',
    tags: ['spreadsheet', 'data', 'google'],
    status: 'approved',
    integration_complexity: 'medium',
    cost_model: 'Free',
    approved_at: '2026-01-27T12:00:00Z',
  },
  {
    ...mockTool,
    id: 'tool-323e4567-e89b-12d3-a456-426614174002',
    name: 'Zapier Webhooks',
    slug: 'zapier-webhooks',
    category: 'automation',
    description: 'Trigger automated workflows via webhooks',
    tags: ['automation', 'webhooks', 'integration'],
    status: 'implemented',
    integration_complexity: 'low',
    cost_model: 'Subscription-based',
    approved_at: '2026-01-20T12:00:00Z',
    implemented_at: '2026-01-25T15:00:00Z',
    assigned_to_id: 'admin-123e4567-e89b-12d3-a456-426614174000',
    assigned_to_username: 'adminuser',
  },
];
